[package]
name = "trash-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

[dependencies.windows]
version = "0.36.1"
features = [
    "alloc",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_Foundation"
]